main: su.nightexpress.excellentcrates.CratesPlugin
version: '${version}'
name: ExcellentCrates
author: NightExpress
desciption: Lightweight, powerful, feature-rich and highly customizable crates plugin.
depend:
  - nightcore
softdepend:
  - EconomyBridge
  - PlaceholderAPI
  - packetevents
api-version: 1.21
folia-supported: true